#!/bin/bash

function header() {
    echo '/* Hello future 12Urenloop maintainer. This file was automatically'
    echo ' * generated by the `make-boxxy-client.sh` script. It would be very'
    echo ' * bad practice to edit this file directly. */'
}

function wrap() {
    MODULE="$1"
    FILENAME="$2"

    echo "var $MODULE = function() {"
    echo '    var exports = {};'
    sed 's/^./    &/' "$2"
    echo '    return exports;'
    echo '}();'
}

OUTPUT='public/js/boxxy-client.js'
echo "Writing $OUTPUT..."

header > "$OUTPUT"
wrap 'boxxy' 'src/boxxy.js' >> "$OUTPUT"
wrap 'client' 'src/client.js' >> "$OUTPUT"
